### ISSUE TITLE
Actual Wan realtime bandwidth not reported on WAN(vlan2) -- appears instead only on eth0

### ISSUE THREAD

**Issue by ymboc** [Jackysi/advancedtomato#104]
**Version**
1.28.0000 -3.0-132 K26ARM USB AIO-64K Netgear R7000

**Prerequisites:**
DHCP Wan Connection

**Screenshots:**
WAN (vlan2) Bandwidth:
![chrome legacy window 12172015 104506 pm](https://cloud.githubusercontent.com/assets/1264665/11888834/3971a89c-a510-11e5-9de8-115187e1a3e4.jpg)
eth0 Bandwidth (representative of actual wan traffic):
![chrome legacy window 12172015 104502 pm](https://cloud.githubusercontent.com/assets/1264665/11888833/396ca34c-a510-11e5-833c-ad3a2b92cbdd.jpg)
(Default) VLan configuration for reference:
![chrome legacy window 12172015 104447 pm](https://cloud.githubusercontent.com/assets/1264665/11888832/396a5484-a510-11e5-8ec5-a79bde59d2d6.jpg)

**Related Internet Chatter**
http://tomatousb.org/forum/t-543266/toastman-vlan-wan-bandwidth-monitor-no-data

**Comment by Jackysi** [comment]
You are aware that the link bellow is related to a year when R7000 didn't even exist or any ARM routers... Not to mention the build is Toastman and my project is based on Shibby. The reported issue has nothing to do with the link... 

Since this is not a GUI related issue, please contact Shibby to take look into it. I am only a Graphical User Interface developer. https://linksysinfo.org/
