### ISSUE TITLE
Access Restriction Rule

### ISSUE THREAD

**Issue by dihego** [Jackysi/advancedtomato#116]
I have applied the attached "PDF = NoACL.PDF" rule but the src IP it is still getting thru

![ssh got thru](https://cloud.githubusercontent.com/assets/17020277/12741722/10117d40-c94d-11e5-80d2-18572ceeadc7.PNG)
[noACL.pdf](https://github.com/Jackysi/advancedtomato/files/113488/noACL.pdf)

Any thoughts of why this rule is not working ?

**Comment by Jackysi** [comment]
I am sorry but this bug is related to Tomato it self and not AdvancedTomato Graphical User Interface. I know its hard to understand but this project is fork of Tomato by Shibby. This project is only Graphical User Interface change (which is actually the hardest part) but the core functionality is unchanged. So for support and issues reports on Firmware/Linux/Core please contact Shibby. I do not have enough knowledge to poke around Firmware so I rather not do that.
