### ISSUE TITLE
MAC Issue

### ISSUE THREAD

**Issue by Aleks-Z** [Jackysi/advancedtomato#131]
In last production build (1.34) i have mac problem. I cann't change any mac address. Check out

NETGEAR WNR3500lv2

**Comment by Jackysi** [comment]
I hope you are kidding with that attitude... I'm aware of the problem....

**Comment by devz3ro** [comment]
I apologize for sending in a bug request on the website. Looks like you're already on top of it, thanks - appreciate your time and effort.

**Comment by santomet** [comment]
Is it going to be fixed anytime soon? Or it is better to downgrade for now, because i really need this feature :(

**Comment by Jackysi** [comment]
Issues are fixed through versions. I don't have the time to actually fix everything as soon as its reported. I did fix the problem but the fix is only available in source code. If you wish you can compile firmware on your own and get the fix now, otherwise waiting for next release is a must. The update was released just yesterday and I'm not going to re-compile every thing today again (takes 36 hours to compile firmware for all routers).

https://github.com/Jackysi/advancedtomato-gui/commit/ee6f2895d46a36687d0c35524522e2ee79ad1023

**Comment by santomet** [comment]
Yeah, sure, that's all i need. Thanks!

**Comment by Aleks-Z** [comment]
Big thanks, @Jackysi . But i couldn't find tutorial for compile of GUI firmware . [Doesn't work.](https://github.com/Jackysi/advancedtomato2/blob/advancedtomato-ac/readme.md) Does exist it ?

**Comment by Jackysi** [comment]
https://bitbucket.org/pl_shibby/tomato-arm/issues/15/compilation-libjson-c-fails
I no longer mess with teaching people how to compile. its the same as Tomato by Shibby.
