### ISSUE TITLE
Huawei WS880 - PPPoE broken

### ISSUE THREAD

**Issue by karevn** [Jackysi/advancedtomato#146]
After upgrading my device to release 135, I found it can't connect with PPPoE anymore. I saw "timeout waiting for PADO packets" in logs, and my ISP told me that the password used is incorrect (even though I made sure it's correct). Downgrading to 132 release solved the problem for me.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
