### ISSUE TITLE
QOS is blocking all trafic in version 134 and 135 (Multi Wan) tested on Asus RT-AC66U

### ISSUE THREAD

**Issue by Tazzmanien** [Jackysi/advancedtomato#149]
QOS is blocking all trafic in version 134 and 135 (Multi Wan) tested on Asus RT-AC66U

1) enable QOS (Keep standard settings)
2) Verify that there is no connection to the internet.

It is working in version 132.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
