### ISSUE TITLE
5GHz and USB conflict

### ISSUE THREAD

**Issue by sevketcaba** [Jackysi/advancedtomato#150]
Tomato Firmware 1.28.0000 MIPSR2-3.1-135 K26 USB Mega-VPN on Linksys E3200, if you disable Core USB Support , 5Ghz Wireless Network is disabled too

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
