### ISSUE TITLE
Broadcast Relay Mode - VPN - Version 3.1-135 

### ISSUE THREAD

**Issue by reginaldogermano** [Jackysi/advancedtomato#151]
Version 3.1-135.
It does not work correctly when I sending broadcast in my Virtual private network (Client) 
My option in PPTP Server - > Broadcast Relay Mode - VPN Clients to Lan .
In the version 3.1-132 it works correctly.

Router: Cisco Linksys EA6500v2
current Version : 1.28.0000 -3.1-132 K26ARM USB AIO-64K

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!

P.S.: Firmware 132 was stable, 133, 134, 135 are experimental.
