### ISSUE TITLE
Devices list & Bw Limiter

### ISSUE THREAD

**Issue by dimas18** [Jackysi/advancedtomato#152]
Inside Device list, some conected devices are disappearing from the list when they are conected on every refresh.

Inside BW Limiter, before on old version i used to work with mac address but on newer version it doesnt work, only if i put the ip address instead it mac.

AdvancedTomato
Tomato Firmware 1.28.0000 MIPSR2-3.1-135 K26 USB Mega-VPN

Linksys E3200

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
