### ISSUE TITLE
Linksys EA6700 only 5GHz network showing

### ISSUE THREAD

**Issue by Pancool** [Jackysi/advancedtomato#153]
I have installed advanced tomato on my router which is a linksys EA6700. 
If I create a VLAN then the router won't use 2.4Ghz frequency and only shows the 5Ghz one. There may be other things causing this issue but this is what I have found to be causing it. I don't know if this is a bug you can easily fix or not but this is the issue I am having.
I don't know if there is a way to solve this or if you have come across this issue before but when searching online I have found other people who seem to be having similar issues to me in that the 2.4Ghz one disappears and only the 5Ghz one is there.
I have also checked and it is not outputting the wireless on 2.4Ghz only 5Ghz when this happens.

Also I have tried installing the older version of advanced tomato and it still does it.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
