### ISSUE TITLE
DVB support AdvancedTomato

### ISSUE THREAD

**Issue by Teldix** [Jackysi/advancedtomato#157]
Hey guys, 

in the past i found a lot of DVB solutions on routers' dd-wrt or advanced tomato. I also started with my asus RT-AC68U router but i stuck in compiling process. There are so many tools and dependencies I could not solve on my ubuntu. I'm a beginner in this area, so that i'm asking you for any hints and support.

Do you know an existing solution or is it even possible to compile it for my router? Can someone of you please compile it for my router?

Thanks and regards,
Tobi

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
