### ISSUE TITLE
Asus RT-AC68U: Major decrease in wireless strength and throughput

### ISSUE THREAD

**Issue by RhysJeffery** [Jackysi/advancedtomato#158]
Your router brand & model: Asus RT-AC68U
Interface version: RT-AC68U-AT-ARM-3.1-135-AIO-64K
Screen shot or error details: Wireless signal drops below 50% on this firmware compared to stock. Throughput is also halved. Wireless AC
How to reproduce the issue/error: Install this filmware and use any wireless settings for AC #

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
