### ISSUE TITLE
5ghz WiFi gone

### ISSUE THREAD

**Issue by pred2k** [Jackysi/advancedtomato#16]
Hi, i played a little around with dnssec (on page http://192.168.1.1/#basic-network.asp).
During setting it on/off, editing dns server ips, changing dnscrypt-proxy the router wasn't available via WiFi  for some short times.
But since one point the 5ghz WiFi was completely gone from the settings and no signal was avavliby anymore. 2.4ghz still works.
Reboot does not bring it back.
Is there anyway to get i back?
My next step would be a config-reset, but i have to save all my konfigs.

Router : Linksys E3200

**Comment by Jackysi** [comment]
I had the same issue, it would seem this is a bug in newer Tomato builds, or my branch. I will try to compare gits again to see if it was my fault. Otherwise this can be fixed by a simple reboot (I had to reboot my R7000 twice to get it working). But this happen to me on Tomato Shibby not AdvancedTomato (yet).

Its hard to figure it out without a log or some other info :/

**Comment by pred2k** [comment]
i fixed it with a config default restore.
But i had to reconfigure everything by hand again.
when i tried to restore my config backup, 5ghz wifi was still gone.

**Comment by Jackysi** [comment]
Its recommended to clear NVRAM every update (without using restore) due to changes in NVRAM coding. The jump from Shibby's update 120 to 123 was huge. It also included a lot of updates regarding drivers/AC standards. Glad you found the problem thanks for sharing!

P.S.: Not just 123, even 119 to 120!
