### ISSUE TITLE
R7000-AT-ARM-3.1-135-AIO-64K: Port FW, DMZ and DDNS WAN IP address do not work

### ISSUE THREAD

**Issue by bhlevca** [Jackysi/advancedtomato#160]
I upgraded from v132 to tomato-R7000-AT-ARM-3.1-135-AIO-64K.trx.

As you mentioned this is an experimental build and indeed it is. I followed all the right install procedures but the firmware does not work in at least 2 aspecte that I found:

1) Port Forwarding does not work
2) DMZ does not work
3) in DDNS the Use IP WAN address always shows 0.0.0.0

I did the NVRAM erase. 

When I returned to 132  everything works fine. This is pointing to a 135 firmware issue.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!

**Comment by bhlevca** [comment]
What if the GUI is at fault because it does not pass the values properly? 
I suggest that you check that before dismissing the report.
