### ISSUE TITLE
E3200 2.4-123 Build Too Big?

### ISSUE THREAD

**Issue by OllieD** [Jackysi/advancedtomato#17]
I am unable to flash the latest AdvancedTomato:
Version 2.4-123
tomato-E3200USB-NVRAM60K-1.28.AT-RT-N5x-MIPSR2-2.4-123-AIO.bin

Error message displayed when flashing is:

File is too big for MTD.

Is there anything you can do or has AdvancedTomato become too big to support this device?

**Comment by Jackysi** [comment]
This is now just AdvancedTomato issue, its common Tomato by Shibby issue since version 121. It will be fixed in next releases.

**Comment by ced2git** [comment]
Same issue.

**Comment by coggy9** [comment]
It looks like AIO won't fit onto the E3200 anymore. V124 of Shibby made a Mega-VPN image instead of AIO now, and it's also true for AT2. Just tried to build from source last night, got a 16.7MB image. Once I figure out how to make a Mega-VPN build without it failing, I'll see if it'll fit.
Edit: I was getting OpenSSL errors when trying "build o e3200", but not "build e3200", for some reason, so I cheated a bit and made AIO use the same build commands as Mega-VPN. Image was built and it 10.3MB. It should fit and work. 
It flashes, but now I have no web GUI. http://i.imgur.com/sFFAlJ5.png

**Comment by Jackysi** [comment]
Here is commit that allows MEGA builds: https://github.com/Jackysi/advancedtomato2/commit/47a464cf1c4ba604527bb94b9e353ee53789a2e6
This issue has been resolved by Shibby. Builds will be available soon!
