### ISSUE TITLE
Dropbear_SFTP_issue

### ISSUE THREAD

**Issue by siorus** [Jackysi/advancedtomato#181]
Hi,

since v132 (ARM maybe others too) I have noticed problem with sftp server while using dropbear. Issue is deeply discussed and explained here [http://www.linksysinfo.org/index.php?threads/sftp-unable-to-connect.72280/](url)

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
