### ISSUE TITLE
Wireless Multicast Not Functioning on ASUS RT-N16 running 3.1-136

### ISSUE THREAD

**Issue by tchentchen** [Jackysi/advancedtomato#182]
I have Wireless Multicast enabled. I can reproduce the problem. When you first enable wireless multicast, it works (e.g. Bonjour). After 15-30 minutes, it stops working. If I disable it and re-enable it, it functions again for 15-30 minutes. I'd guess that whatever service Tomato is restarting when wireless multicast is enabled is crashing or hanging after 15-30 minutes.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
