### ISSUE TITLE
backup/restore configuration

### ISSUE THREAD

**Issue by aln-1** [Jackysi/advancedtomato#204]
if you do backup/restore configuration with hard reset in between then these settings are than gone:
access restrictions
pptp server

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
