### ISSUE TITLE
ASUS RT-N16 on Version: 3.2-137 DNS Issue

### ISSUE THREAD

**Issue by aleclair840** [Jackysi/advancedtomato#205]
Noticed a DNS'ing issue off and on with  Version: 3.2-137 on a ASUS RT-N16

Tried loading site on devices below
Wired Desktop
Wired Xbox One
Wireless Samsung S5 cell phone

easports.com sign in page dns did not resolve on all devices wired and wireless.. 
did a netstat get pages IP 
159.153.228.137
159.153.228.77

i was able to both ping and tracert that ip. 
issue will resolve itself after time then come back.. 

Swapped to a asus rtn-12 on stock firmware page loads, manual connection to modem page loads.. just through my rt-n16 on advanced tomato giving issue.

Originally used ISP DNS servers tested googles DNS servers aswell 8.8.8.8 and 8.8.4.4

Downgraded firmware to prev version 3.2-136 and testing now. 
Possible its hardware issue but it started same time approx as firmware update was applied so suspecting its firmware.. 

Issue comes and goes no pattern that seems to cause it then same for resolve it just seems to start working..  Power cycling router does nothing, did some winsock resets via command line and issue remains.. Come back few hours later or next day try again and it loads.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
