### ISSUE TITLE
QoS Unlisted Device affecting listed device. 

### ISSUE THREAD

**Issue by jalfy** [Jackysi/advancedtomato#215]
Device: Linksys e2500v3
Firmware: 3.3-138
*No Screenshot (To follow I guess, router is physically very far away from me now)

The problem: I was making a B/W list using devices MAC address as identification, and it doesn't look like it's working. Even if the device is listed on the list, it still gets the same treatment as for those unlisted. I tried using IP addresses assigned to devices instead of MAC address, and it seems to be working. 

To replicate: From Factory Default, go to QoS basic, assign the necessary Tx and Rx rate, go to B/W, assign devices using MAC Address as Identification, set atleast different rules to each devices from highest to lowest wih different Download and upload. Enable the 'unlisted' and provide the necessary restrictions. Test devices(clients) within the list and outside the list. (I get the same speed result from an unlisted and listed device) 

I tried to Google some answers for my query, but it seems there's no one who's experiencing the same problem as I. 

P.S. loving the new UI and the work you've done to this project!

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
