### ISSUE TITLE
The router doesn't connect to 3G/4G Internet automatically.

### ISSUE THREAD

**Issue by mrAlexis** [Jackysi/advancedtomato#216]
Device: NETGEAR R7000
Firmware: 3.3-138
*No Screenshot
The problem: I use 4G modem Megafon M100-4(Huawei E3272) with Megafon SIM card installed.
After Advanced Tomato for NETGEAR R7000 ver. 3.3-138 have booted, for establishing connection I have to press in the status menu, under WAN section, the CONNECT button, after few seconds, RELEASE button, then RENEW, and then RELEASE again, and RENEW. After that the router connects through modem to the internet provider.

To replicate: To connect Huawei E3272 modem with SIM card installed, from Factory reset, to choose settings in Basic -> Network -> WAN type: 4G Modem, to enter an internet provider's settings, and apply them.

The router should connect to the intrnet automatically, but it's doesn't.

Hope this issue is not hard to fix.

Thank you for your job!

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
