### ISSUE TITLE
RT-AC66U, 5Ghz Wifi not turned off by stealthMode script

### ISSUE THREAD

**Issue by puschlj** [Jackysi/advancedtomato#224]
Hello,

**Router**
Asus RT-AC66U

**FW Version**
Tomato Firmware 1.28.0000 MIPSR2-3.3-138 K26AC USB AIO-64K

**Issue**: 
- stealthMode off doesn't turn off the 5Ghz Wifi led.
- this is not working: wl -i eth2 leddc 1

Best regards

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
