### ISSUE TITLE
SMB shares disconnect while torrenting

### ISSUE THREAD

**Issue by loalcat** [Jackysi/advancedtomato#227]
Router: ASUS RT-AC68U
Interface version: v3.3-138

I have USB 2.0 2TB portable HDD connected to the router. Enabled SMB share on it and connected network drive to Windows 10 Pro PC. Using network drive as torrent-download directory from PC (more than 40 torrents (50% active)). Network drive randomly disconnects causing an error in torrent client (utorrent latest). Tested it on 3 other PC-s and got the same thing. I think there is a bug in router firmware while handling multi threaded requests to drive.

![usbconf](https://cloud.githubusercontent.com/assets/22234942/18582113/324721ea-7c0c-11e6-8651-07fca7bf7a9d.JPG)

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
