### ISSUE TITLE
WAN performance decrease in bridged mode

### ISSUE THREAD

**Issue by gstadler** [Jackysi/advancedtomato#229]
I have a 1 GB/200 MB wan connection on the router of my ISP provider. This router is bridged to an ASUS RT-N16 with the latest advanced tomato firmware. 

Settings: 

WAN disable, 
Bridge WAN port to br0, 
the wan port is connected to LAN port of the router of the ISP
Gateway/DNS IP is 192.168.1.1 
Asus IP address is 192.168.1.2 
ISP router IP address is 192.168.1.1 
Computer is connected to the LAN1 port of ASUS, IP is static 192.168.1.3

Download performance on the ASUS with tomato is between 10%-50% of my wan connection. Upload speed is not affected. All ports are operating in 1 GB mode on the Asus.

With all other things unchanged (ISP router & computer connection, cables, etc) and using the latest Asus firmware on the RT-N16 in Access Point mode, the download speed stays 1 GB on the ASUS. 

Both setups are "clean". (after factory reset, firmware flash).

I suspect I miss something in my tomato setup when bridging it to the other router, something which is done in the setup of the Asus firmware in AP mode, but I don't know what it could be.

**Comment by Jackysi** [comment]
Awesome (Y). This is not a support FORUM!

This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
