### ISSUE TITLE
Assigning ports to VLANs doesn't work

### ISSUE THREAD

**Issue by Goldfish64** [Jackysi/advancedtomato#230]
The latest version 3.3-138 doesn't retain the VLAN assignments for each port after a reboot. Router is a Linksys E3200. Creating a new VLAN and then moving a port to that VLAN results in this after a reboot:
![vlanports](https://cloud.githubusercontent.com/assets/6315508/18685785/12cf831c-7f3f-11e6-8ec3-2e93d875f1d1.png)

An "nvram show" verifies that the port is part of both VLANs, but I'm not sure if it has connectivity on both.

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
