### ISSUE TITLE
Not able to turn USB support back on after disabling.

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#235]
Disabled. Able to check the box to reenable but save button fails to register click. Tried on multiple browsers; Firefox (Linux) and Iridium (Windows).
Clean installed same firmware with NVR wipe. USB stick detected correctly.
Reload old configuration, reboot, USB stick not detected.

Do you have a work-around or command line hot fix to get it going again for the moment, please?
I can't figure out the format of the binary config file. Guessing that the module no longer installed.

Thank you.

**Comment by Jackysi** [comment]
You should really contact Shibby regarding this matter. The AdvancedTomato is same behind the GUI and your issue is entirely Tomato related. Its possible there is a driver issue, I have no idea. There is also matter of router which every one is different and you don't even provide the name of yours. Anyway closing this.
