### ISSUE TITLE
error when drag a (>4GB file) to ftp or share server 

### ISSUE THREAD

**Issue by ivanchy** [Jackysi/advancedtomato#243]
I am using the Netgear R6250 Version 3.3-138 firmware, i found that when i drag a >4GB file to the ftp server, it will show the below error. My USB3.0 format is exFAT,  what solution can i solve it ? thanks :) 

![error](https://cloud.githubusercontent.com/assets/16917916/19656761/cb4fac76-9a53-11e6-850c-e4a3758d6181.JPG)

It said the connection was reset

**Comment by Jackysi** [comment]
First off, this is firmware issue so turn to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!

Secondly, I'm pretty sure ARM is 32bit CPU which doesn't support integers above 4GB, meaning FTP doesn't support files larger than 4GB. So the problem is not filesystem but the CPU instruction set.
