### ISSUE TITLE
Can't change VLAN settings

### ISSUE THREAD

**Issue by elclaudio** [Jackysi/advancedtomato#244]
Hi

It seem's I can't remove a LAN port from the default VLAN 1 and affect it to another VLAN; well it appear to works in the gui, the router ask me to reboot and when I go back to VLAN advanced settings, the port I unchecked is still selected in VLAN 1, as well as the new wanted port...

in fact, I can't remove any LAN port from default VLAN, after reboot, the VLAN aren't changed from default configuration. NVRAM has been cleared after firmware installation.

Router model : netgear R7000
Advanced tomato version : Tomato v1.28.0000 -3.3-138 K26ARM USB AIO-64K

![clipboard01](https://cloud.githubusercontent.com/assets/6136831/19657945/54b10a92-9a26-11e6-8aff-a46cbb52400c.jpg)

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!

**Comment by elclaudio** [comment]
thanks
Btw, just tested, it works as expected with toastman's tomato build, tomato-R7000-9007.8Toastman-ARM-VPN-64K

**Comment by Jackysi** [comment]
Toastman != Shibby / AdvancedTomato
