### ISSUE TITLE
Limitations for 1000 Mbps connection

### ISSUE THREAD

**Issue by mihaibuduleanu** [Jackysi/advancedtomato#247]
Seems that Tomato is somehow limiting the connection speed. Regular Asus/Merlin firmwares on AC66U are showing decent speeds(>700 Mbps) in a speedtest but when using Tomato it's barely over 100.

http://www.speedtest.net/result/5744720997.png

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
