### ISSUE TITLE
Router hangs on boot when connected to modem with dnsmasq restarting

### ISSUE THREAD

**Issue by RevRagnarok** [Jackysi/advancedtomato#248]
This one doesn't make much sense, but if I am connected to the modem on boot, it just hangs.

I can `ssh` in, and I see that "`service dnsmasq restart`" is an active application and `init` is pegged at 100% CPU. If I check the nvram, I see that `action_service` is stuck at `dnsmasq-restart` (or maybe `dnsmasq-restart-c` I forget). Nothing `dnsmasq` related shows up in `/var/log/messages` so I don't think it ever kicks off.

To fix it, I unplug the modem and reboot the router. I've tried manually unsetting and blanking the `action_service` and killing the stuck service call, but it doesn't continue. It's before `httpd` even launches, so I'm happy enough that I can at least `ssh` in.

Asus RT-N16 v3.3-138-AIO

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
