### ISSUE TITLE
Wifi AC, and Channel Width 40/80 MHz

### ISSUE THREAD

**Issue by DelBierzo** [Jackysi/advancedtomato#249]
v3.3-138 AIO-64K "Netgear R7000"

Why in "Wireless Network Mode", only have "Auto /  A Only / N Only", where is N AC, and AC Only.

And in "Basic settings / Network / Wireless (5 GHz / eth2)" i can select Channel Width 80Mhz, but in "Advanced Settings / Virtual Wireless" when select "eth2 (wl1)" the same happens no AC, but now in Channel Width only can choose 20 and 40Mhz, there is not 80 Mhz, and if save changes in Status / Overview my rate is now 72 Mbps, you need to go again at "Basic settings / Network / Wireless (5 GHz / eth2)" select 80 Mhz channel width and save to could rate at 325 Mbps in my case with a Experia Z1.

**Comment by Jackysi** [comment]
I wonder that too. I kinda guessed its because Wi-fi drivers are not "OPEN" and so the devs are limited to options that "CLOSED" driver provides. Because of kernel version and Tomato being old as fk I'm pretty sure most Wi-fi features don't work properly they just "WORK". Look how many more options has the original firmware regarding the Wi-fi. 

## 

AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
