### ISSUE TITLE
dns

### ISSUE THREAD

**Issue by ssavickiy** [Jackysi/advancedtomato#259]
After some time the work stops working dns. ping by ip work. ping on the nameserver - do not work. reboot does not help. reset helps for a while.

![default](https://cloud.githubusercontent.com/assets/23532871/20407805/f26120fa-ad23-11e6-8038-36542ec22787.JPG)
![1](https://cloud.githubusercontent.com/assets/23532871/20407806/f2620916-ad23-11e6-8e31-1728640eea07.JPG)
![3](https://cloud.githubusercontent.com/assets/23532871/20408098/1639871e-ad25-11e6-9172-61f1f3394b48.JPG)

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues.  

From AdvancedTomato.com:
Github AdvancedTomato (GUI ONLY) issue tracker: https://github.com/Jackysi/advancedtomato/issues
Bitbucket Tomato by Shibby (firmware) issue tracker: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
