### ISSUE TITLE
memory card & log 

### ISSUE THREAD

**Issue by ssavickiy** [Jackysi/advancedtomato#260]
does not want to be saved to the memory card Syslog (does not create a log file itself and if you change the path to the memory card and save the changes then he opens the log through the gooey empty), although Bandwidth and IP Traffic Monitoring perfectly stored on it

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues.  

From https://advancedtomato.com/contact :
Github AdvancedTomato (GUI ONLY) issue tracker: https://github.com/Jackysi/advancedtomato/issues
Bitbucket Tomato by Shibby (firmware) issue tracker: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
