### ISSUE TITLE
command ipset create hangs

### ISSUE THREAD

**Issue by f1-outsourcing** [Jackysi/advancedtomato#261]
```
modprobe ip_set
ipset create test hash:ip
```
hangs on the console

Linux f1rt1 2.6.36.4brcmarm #5 SMP PREEMPT Tue Aug 16 22:49:47 CEST 2016 armv7l GNU/Linux
tomato-RT-AC68U-AT-ARM-3.3-138-AIO-64K.trx

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues.

From https://advancedtomato.com/contact :
Github AdvancedTomato (GUI ONLY) issue tracker: https://github.com/Jackysi/advancedtomato/issues
Bitbucket Tomato by Shibby (firmware) issue tracker: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
