### ISSUE TITLE
Router reboots when mirroring video between Chromecast and computer

### ISSUE THREAD

**Issue by jdksgit** [Jackysi/advancedtomato#272]
Router reboots often when mirroring video from computer to Chromecast through Chrome browser. Other instances when this happens is during Dropbox or Drive sync. Below is the router info and log error

Router: Linksys E3200
Version: Advanced Tomato 1.28.0000 MIPSR2-3.4-138 K26 USB Mega-VPN

Dec 14 01:10:07 unknown daemon.err apcupsd[379]: apcupsd FATAL ERROR in linux-usb.c at line 609 Cannot find UPS device -- For a link to detailed USB trouble shooting information, please see <http://www.apcupsd.com/support.html>.
Dec 14 01:10:07 unknown daemon.err apcupsd[379]: apcupsd error shutdown completed

**Comment by Jackysi** [comment]
The error bellow has nothing to do with your router crashing. Also this problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware modification. Issue as previously stated is irrelevant to the Graphical user interface but is actual firmware issue.

From https://advancedtomato.com/contact :
Github AdvancedTomato (GUI ONLY) issue tracker: https://github.com/Jackysi/advancedtomato/issues
Bitbucket Tomato by Shibby (firmware) issue tracker: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
