### ISSUE TITLE
Slow Speeds with Advanced tomato

### ISSUE THREAD

**Issue by jimmyfi** [Jackysi/advancedtomato#276]
I have 350 megs internet connection but while going trough I only get. Test was done with LAN cable 

Testing download speed........................................
Download: 175.45 Mbits/s
Testing upload speed..................................................
Upload: 16.17 Mbits/s

I have Asus RT-AC66u router and it didnt have this performance issue before.
I tested my connection with out the AC and the speedtest gave 330Mbit/s

Could i have some setting wrong or something? I dont have QoS on atleast :)

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato by Shibby and so its not an actual firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues.

From https://advancedtomato.com/contact :
Github AdvancedTomato (GUI ONLY) issue tracker: https://github.com/Jackysi/advancedtomato/issues
Bitbucket Tomato by Shibby (firmware) issue tracker: https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
