### ISSUE TITLE
Website doesn`t work with Internet Explorer 11

### ISSUE THREAD

**Issue by ForumSchlampe** [Jackysi/advancedtomato#30]
•Your router brand & model
ASUS RT-N18U

•Interface Version
2.4-123 K26ARM USB AIO-64K

•Screen shot or error Details
•How to reproduce the issue/error
Many config pages dont work like expected:
http://router.lan/#basic-network.asp
IE: New IP Address doesnt apply after press save
Opera: All works like expected

http://router.lan/#nas-usb.asp
http://wurstrouter.lan/#nas-ftp.asp
http://wurstrouter.lan/#nas-samba.asp
http://wurstrouter.lan/#nas-bittorrent.asp
http://wurstrouter.lan/#nas-nginx.asp
http://router.lan/#admin-access.asp
http://wurstrouter.lan/#advanced-dhcpdns.asp
http://wurstrouter.lan/#advanced-restrict-edit.asp
IE: just a blank page
Opera: works like expected

And so on, in the whole it is unusable with Internet Explorer

**Comment by Jackysi** [comment]
This is rather strange since I just tested my Router GUI on IE11 and it works fine. I visited all the pages in question and they work normally. Do you get any errors in the developer console?

[image](https://cloud.githubusercontent.com/assets/2860965/5524370/4658bc24-89d4-11e4-85b7-1c2f1e3ff9a5.png)
