### ISSUE TITLE
QoS broken

### ISSUE THREAD

**Issue by simonz21** [Jackysi/advancedtomato#307]
I've been using the latest Shibby up till now and have only just switched over to AT. But there is a problem. On my N16 QoS no longer works. It looks like nearly all my traffic is being labelled as the default classification P2p/bulk and so I'm only getting a fraction of my bandwidth, instead of the 70% ceiling I have actually fixed.

In fact, no matter what I do, everything (100%) of my traffic is labelled p2p/bulk

![image](https://cloud.githubusercontent.com/assets/26865660/24656444/e43fc932-1942-11e7-8a51-0653947899a4.png)

**Comment by Jackysi** [comment]
Did you clean NVRAM?

**Comment by simonz21** [comment]
Yup…sorry, went back to SHibby in the end…

**Comment by Kazula** [comment]
I can remember that there was an entry in qos-classify.asp which mentioned UDP 1-65535 as Crawl P2P.
Lately, Google (also Youtube and other Google services) sends their data via QUIC (UDP) so that I think that the data gets classified as P2P/Bulk.

You could try to block the port 443 for UDP in #advanced-restrict.asp to disable QUIC.
