### ISSUE TITLE
VPN Client password too small

### ISSUE THREAD

**Issue by antonioribeiro** [Jackysi/advancedtomato#308]
Pretty much all of my passwords are 100 chars, since I don't really type them anymore. But the interface is capping them to 50, and telling nothing about it. What I think we should try to do here:

- Try to make passwords really larger, or at least 1024 chars (which may somehow be a problem at some point)

- If it's not possible to make them larger at all, allow typing any password size and give a message telling the password is too large.

The problem I had was that I just pasted the password, my VPN was connected, but I wasn't authenticated, because of the wrong password. So I got a green in the vpn client but in the logs I got "AUTH: Received AUTH_FAILED control message", which is, actually, another issue.

**Comment by Jackysi** [comment]
This issue is unrelated to the AdvancedTomato GUI Modification. This whole project is only GUI modification meaning I don't change any internal software/code related to the routing it self. This project is goaling to stay on same state as Shibby's Tomato and for that reason this report is completely useless here. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
