### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by vistad** [Jackysi/advancedtomato#326]
Hello,

I am using TomatoUSB W1800R_AT-RT-AC6x-3.4-140-VPN-64K.trx on Tenda W1800R router for 2 days already! :) So far so good!

When I found Tomato supports Tenda W1800R, I bought it and installed TomatoUSB the next day.

My first feelings - it works great, but still is prone to freezing.

Today I found it does not see the USB drive. I rebooted it a few times to no avail. I was getting desperate - and then I had an idea I should do a cold restart. I switched it off, waited for 10 seconds and switched it on. And this time it had worked and at last had found its USB drive, sonofabitch! Regular, hot restart - is not enough.

Can we increase its reboot pause by a few seconds - e.g. 5 sec.?

**Comment by Jackysi** [comment]
This issue is unrelated to the AdvancedTomato GUI Modification. This whole project is only GUI modification meaning I don't change any internal software/code related to the routing it self. This project is goaling to stay on same state as Shibby's Tomato and for that reason this report is completely useless here. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open
