### ISSUE TITLE
VPN on off switch

### ISSUE THREAD

**Issue by Stevefiltrete** [Jackysi/advancedtomato#368]
I have a Netgear R7000 router. The original firmware had a switch where I could turn the VPN on and off easily but it wasn't compatible with my VPN service. I decided to flash the DD-WRT firmware but it has no way to turn the VPN on and off. My wife likes to stream Amazon so the DD-WRT has created a problem that I have to solve. Does the Tomato firmware have the ability to toggle between VPN on and off?

Thanks;
Steve

**Comment by jsconsultancy** [comment]
Hi Steve, what you could do is instead of toggling VPN on and off, just policy route the ip address of the device watching amazon through the VPN and everything else through default WAN/Internet. I do that with Roku going through VPN and everything else normal through WAN/INTERNET (in order not to slow down my internet access).
