### ISSUE TITLE
Netgear NightHawk 1900 Bricked

### ISSUE THREAD

**Issue by Ajkula999** [Jackysi/advancedtomato#47]
Hi,
I flashed my router from Kong to ”tomato-R7000-initial-126” and am unable to login. After reading few articles I realized that Kong uses encrypted passw and tomato doesn’t, therefore my current password is unknown I tried 30-30-30, tftp put command using Win7 and TFTPD64 however nothing is working.
Is there any solution or suggestion on how to fix this?

Thanks in advance

**Comment by Jackysi** [comment]
Please don't use issue tracker for these sort of problems. This is not AdvancedTomato issue. 
http://linksysinfo.org or email me in future. Honestly I have no idea how to fix this, but your best bet is somehow forcing NVRAM reset. Since I don't have enough knowledge to tell you how to do that (I use USB-TTL cable on my R7000) please attempt to contact developer Shibby who has all the knowledge to help you.
