### ISSUE TITLE
Bug associated to "iproute2 update to 3.19.0 (from iproute2-ss111010 to iproute2-ss150210)"

### ISSUE THREAD

**Issue by ghost** [Jackysi/advancedtomato#59]
Hi,

First of all. Thanks for a brilliant firmware!

I have located a bug accociated to the release of version 2.6-127 and all following versions of Tomato. The bug is located to 'iproute2 update to 3.19.0 (from iproute2-ss111010 to iproute2-ss150210)'

Executing the command "ip link show dev lo" does return following error: 

"RTNETLINK answers: Invalid argument
Cannot send link get request: Invalid argument"

The error can be reproduced on any version from 2.6-127 and above. On version 2.5-124 the ip link show dev lo command returns what is expected.

I use the Netgear R7000 router. The bug is found in combination with Firewall Builder. Installing the fw script on the router fails due to upgrade to iproute2-ss150210.
For your information the issue does not seems to exist on the latest asuswrt firmware. Either I need to install asuswrt or stick to version 2.5-124 of Tomato. Alternative skip FW builder, but that ain't gonna happen easily ;-)

Please let me know if the iproute2 issue can be fixed in a coming update/release of Tomato.

Many thanks
Carsten

**Comment by Jackysi** [comment]
I am sorry to inform you that the issue is not related to AdvancedTomato Interface but Tomato itself. Please address the issue to Shibby since he is the main developer of Tomato mods I only fork his work and create GUI for it. If you have the knowledge you can create a patch/pull request to upgrade iproute and I will merge my work with it. Otherwise we'll have to wait for Shibby's update on this.
