### ISSUE TITLE
UPnP over Wifi

### ISSUE THREAD

**Issue by kresomania** [Jackysi/advancedtomato#72]
Version: 1.28.0000 -2.9-131 K26ARM USB AIO-64K
Router: Netgear R7000
Menu: Port Forwarding -> UPnP/NAT-PMP -> Settings

I'm not able to activate UPnP over Wireless. It means uTorrent over Wifi won't work.

It's also strange that only connected ports (check boxes) can be activated.

**Comment by Jackysi** [comment]
This issue is not related to AdvancedTomato Interface but Tomato itself. Please address the issue to Shibby since he is the main developer of Tomato mods I only fork his work and create GUI for it.

Checkboxes are enabled for existing interfaces only. This is the way it supposed to work (the way Shibby implemented it) so its working correctly. Regarding Wifi & UPnP I have same issue and waiting for fix since Shibby's 120 version...
