### ISSUE TITLE
OpenVPN problem which can cause 2.4GHz band support no longer available

### ISSUE THREAD

**Issue by cchungcc** [Jackysi/advancedtomato#74]
Advance Tomato version: 2.9-131 with Tenda W1800R router.
I noticed that the 2.4GHz support will no longer available after I enabled the OpenVPN and then reboot the router.  As long as I do not reboot the router, the 2.4 GHz support will still be working.  As long as I reboot or power cycle the router after I enabled the OpenVPN support, the 2.4 GHz wireless band support will no longer show up or support from within the router.  So I have to restore all my setting prior to the OpenVPN support setting; otherwise, I will never get the 2.4 GHz band support back in working condition.
For OpenVPN, I enabled with all the key fields entered.  I have a feeling that the keys data are being overwritten some of the internal data fields within the router.  I also noticed that the OpenVPN will not execute correctly after I entered all the keys and expected setting.  The OpenVPN will not start correctly.  Once the OpenVPN failed start the service and I rebooted the router, the 2.4 GHz band support is no longer available and support with the UI fields.
So I cannot enable OpenVPN if I still want to use 2.4 GHz band support within the router itself.  This is definitely a bug within the base code.  I also tried with the latest Tomato Shibby version and it had the same result and behavior as the Advance Tomato version.

**Comment by Jackysi** [comment]
I apologize for sounding ungrateful or something, but I am not a Tomato developer. Well I do work on Tomato all the time but I don't change the base code at all. I only work on Graphical User Interface, basically front end. So please report these issues to Shibby and hold your GUI issues for me. I understand this may sound a little disrespectful or strange. I do not intend to do be just that.

I think it's described pretty well on the web site what AdvancedTomato is. Thank you for report anyhow, but I have to close it because its unrelated to the GUI.
