### ISSUE TITLE
UI elements missing on desktop

### ISSUE THREAD

**Issue by spelaben** [Jackysi/advancedtomato#78]
Hi Jackysi,

I think I discovered one more issue in the UI (AC66U).
I can use all features and access all configuration menus on my Chromebook. On my desktop PC using Windows 10 x64 (tested Chrome and Internet Explorer) it looks like this:

![ui](https://cloud.githubusercontent.com/assets/4146302/10411570/bfade190-6f6a-11e5-95e9-8e1b8f048f84.png)

The following errors are shown in the developer menu:

![error](https://cloud.githubusercontent.com/assets/4146302/10411572/cece5fe2-6f6a-11e5-9c93-2881a46aebfd.png)

Best regards

**Comment by Jackysi** [comment]
Mm these are not UI issues at all =). At this report user: https://github.com/Jackysi/advancedtomato2/issues/76 experianced very simmilar issue and there is also reports that IPv6 configuration causes timeouts to Web Interface, eather way original Tomato has the same issues because they're not related to the graphical interface :). But thanks for report!

P.S.: As developer console says the connection gets reset/timeout which is why the interface goes "wtf" mode. Its missing its required files because they didn't load. Chromebook is running Chrome so either way the issue would persist over both devices if it was UI problem.
