### ISSUE TITLE
2 Core support

### ISSUE THREAD

**Issue by asharpaev** [Jackysi/advancedtomato#91]
I have Huawei WS880v1 and with PPTP internet connection have only ~200 Mbit/s because it use only one core but I have plan with 250Mbit/s

**Comment by Jackysi** [comment]
I am sorry but this bug is related to Tomato it self and not AdvancedTomato Graphical User Interface. I know its hard to understand but this project is fork of Tomato by Shibby. This project is only Graphical User Interface change (which is actually the hardest part) but the core functionality is unchanged. So for support and issues reports on Firmware/Linux/Core please contact Shibby. I do not have enough knowledge to poke around Firmware.
