### ISSUE TITLE
Some bugs of Virtual Wireless Interfaces

### ISSUE THREAD

**Issue by F9y4ng** [Jackysi/advancedtomato#94]
Hi, I think I found Advanced Tomato of BUGS. I set the Virtual Wireless Interfaces, trying to add or modify Virtual Wireless (such as wl0.1, wl0.2, wl0.3 or wl1.1, wl1.2, wl1,3 etc.), then save the setting. When the saving operation is completed, Basic settings - Network - Wireless (5 GHz / eth2) in the Channel Width is automatically changed to 20M, whether I had it set to any value will change automatically. I think this should be a BUG, you check it?

**Comment by Jackysi** [comment]
I am sorry but this bug is related to Tomato it self and not AdvancedTomato Graphical User Interface. I know its hard to understand but this project is fork of Tomato by Shibby. This project is only Graphical User Interface change (which is actually the hardest part) but the core functionality is unchanged. So for support and issues reports on Firmware/Linux/Core please contact Shibby. I do not have enough knowledge to poke around Firmware.

**Comment by F9y4ng** [comment]
thx.

2015-11-30 0:41 GMT+08:00 Jacky Prahec notifications@github.com:
